DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  prenom VARCHAR(256) NOT NULL DEFAULT '',
  nom VARCHAR(256) NOT NULL DEFAULT '',
  pseudo VARCHAR(256) NOT NULL DEFAULT '', 
  mail VARCHAR(256) NOT NULL DEFAULT '',
  photo VARCHAR(256) NOT NULL DEFAULT 'icon.png',
  abonnes INT(16) NOT NULL DEFAULT 0,
  suivis INT(16) NOT NULL DEFAULT 0,
  naissance DATE,
  password CHAR(70) NOT NULL DEFAULT '', 
  isAdmin BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  UPDATE users SET admin=true WHERE nickname='didodito';